---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-explore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: demo-app-ui
        tier: frontend
    spec:
      containers:
        - name: demo-app-ui
          image: harbor.tools.beyondelastic.demo/vmware-explore/vmware-explore-app:v1
          ports:
          - containerPort: 80


