---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-explore-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: demo-app-ui
        tier: frontend
    spec:
      containers:
        - name: demo-app-ui
          image: harbor.vlab2.uhtec.de/build/vmworld:1.0
          ports:
          - containerPort: 80


